// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `byte_to_line`, `byte_to_utf16_offset`, `byte_to_utf16`, `char_at_byte`, `char_to_utf16_offset`, `find_word_boundary_backward`, `find_word_boundary_forward`, `from_char`, `from_file`, `get_state`, `line_chars`, `line_to_byte`, `max_line_utf16_len`, `new`, `new`, `rope_len_lines`, `utf16_to_byte`, `utf16_to_char_offset`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CharClass`, `EditorState`, `SearchMatch`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

RopeMetrics getMetrics({required RopeInstance instance}) =>
    RustLib.instance.api.crateApiGetMetrics(instance: instance);

RopeInstance createRopeInstance({required String text}) =>
    RustLib.instance.api.crateApiCreateRopeInstance(text: text);

void insert(
        {required RopeInstance instance,
        required int offsetUtf16,
        required String text}) =>
    RustLib.instance.api.crateApiInsert(
        instance: instance, offsetUtf16: offsetUtf16, text: text);

void delete(
        {required RopeInstance instance,
        required int startUtf16,
        required int endUtf16}) =>
    RustLib.instance.api.crateApiDelete(
        instance: instance, startUtf16: startUtf16, endUtf16: endUtf16);

/// Combined replace operation: delete a range and insert text atomically.
void replace(
        {required RopeInstance instance,
        required int startUtf16,
        required int endUtf16,
        required String text}) =>
    RustLib.instance.api.crateApiReplace(
        instance: instance,
        startUtf16: startUtf16,
        endUtf16: endUtf16,
        text: text);

String getText({required RopeInstance instance}) =>
    RustLib.instance.api.crateApiGetText(instance: instance);

String getTextRange(
        {required RopeInstance instance,
        required int startUtf16,
        required int endUtf16}) =>
    RustLib.instance.api.crateApiGetTextRange(
        instance: instance, startUtf16: startUtf16, endUtf16: endUtf16);

int getLineCount({required RopeInstance instance}) =>
    RustLib.instance.api.crateApiGetLineCount(instance: instance);

/// Optimized function to get document length in UTF-16 code units
int getLengthUtf16({required RopeInstance instance}) =>
    RustLib.instance.api.crateApiGetLengthUtf16(instance: instance);

int getLineStartOffsetUtf16(
        {required RopeInstance instance, required int lineIndex}) =>
    RustLib.instance.api.crateApiGetLineStartOffsetUtf16(
        instance: instance, lineIndex: lineIndex);

/// Batch API: Returns UTF-16 start offsets for a contiguous range of lines.
List<int> getLineStartOffsetsBatch(
        {required RopeInstance instance,
        required int startLine,
        required int endLine}) =>
    RustLib.instance.api.crateApiGetLineStartOffsetsBatch(
        instance: instance, startLine: startLine, endLine: endLine);

/// Batch API: Returns minimap density data for multiple lines.
/// Eliminates string serialization overhead for minimap rendering.
/// For each line, computes leading whitespace, content length, and emptiness
/// directly on the Rust side.
List<MinimapLineDensity> getMinimapDensityBatch(
        {required RopeInstance instance, required List<int> lineIndices}) =>
    RustLib.instance.api.crateApiGetMinimapDensityBatch(
        instance: instance, lineIndices: lineIndices);

int getLineAtOffsetUtf16(
        {required RopeInstance instance, required int offsetUtf16}) =>
    RustLib.instance.api.crateApiGetLineAtOffsetUtf16(
        instance: instance, offsetUtf16: offsetUtf16);

/// Returns only the requested line, avoiding a full document clone.
String getLineText({required RopeInstance instance, required int lineIndex}) =>
    RustLib.instance.api
        .crateApiGetLineText(instance: instance, lineIndex: lineIndex);

List<String> getLinesTextBatch(
        {required RopeInstance instance, required List<int> lineIndices}) =>
    RustLib.instance.api.crateApiGetLinesTextBatch(
        instance: instance, lineIndices: lineIndices);

List<int> search(
        {required RopeInstance instance,
        required String pattern,
        required bool caseSensitive,
        required bool isRegex}) =>
    RustLib.instance.api.crateApiSearch(
        instance: instance,
        pattern: pattern,
        caseSensitive: caseSensitive,
        isRegex: isRegex);

Future<RopeInstance> createRopeInstanceAsync({required String text}) =>
    RustLib.instance.api.crateApiCreateRopeInstanceAsync(text: text);

/// Load a rope directly from a file path without loading entire content into Dart first.
/// For single-line files, pass max_chars to limit how much is loaded (for viewport buffering).
/// Pass None for max_chars to load the entire file (for normal multi-line files).
Future<RopeInstance> createRopeInstanceFromFile(
        {required String path, int? maxChars}) =>
    RustLib.instance.api
        .crateApiCreateRopeInstanceFromFile(path: path, maxChars: maxChars);

Future<String> getTextAsync({required RopeInstance instance}) =>
    RustLib.instance.api.crateApiGetTextAsync(instance: instance);

int getContentHash({required RopeInstance instance}) =>
    RustLib.instance.api.crateApiGetContentHash(instance: instance);

/// Get text for a contiguous range of lines in a single FFI call.
String getLinesTextRange(
        {required RopeInstance instance,
        required int startLine,
        required int endLine}) =>
    RustLib.instance.api.crateApiGetLinesTextRange(
        instance: instance, startLine: startLine, endLine: endLine);

/// Get a text chunk starting at a UTF-16 offset with a maximum length.
/// Useful for slicing wide lines for viewport rendering without copying
/// the entire line content.
String getTextChunk(
        {required RopeInstance instance,
        required int startUtf16,
        required int maxLength}) =>
    RustLib.instance.api.crateApiGetTextChunk(
        instance: instance, startUtf16: startUtf16, maxLength: maxLength);

/// Detect the dominant indentation style in the document by sampling lines.
IndentInfo detectIndentation({required RopeInstance instance}) =>
    RustLib.instance.api.crateApiDetectIndentation(instance: instance);

int getLineIndentation(
        {required RopeInstance instance, required int lineIndex}) =>
    RustLib.instance.api
        .crateApiGetLineIndentation(instance: instance, lineIndex: lineIndex);

/// Search for a pattern only within a specific line range.
/// Returns UTF-16 offsets as pairs [start, end, start, end, ...].
/// More efficient than full document search when you only need results
/// for visible lines.
List<int> searchInRange(
        {required RopeInstance instance,
        required String pattern,
        required int startLine,
        required int endLine,
        required bool caseSensitive,
        required bool isRegex}) =>
    RustLib.instance.api.crateApiSearchInRange(
        instance: instance,
        pattern: pattern,
        startLine: startLine,
        endLine: endLine,
        caseSensitive: caseSensitive,
        isRegex: isRegex);

/// Get the character class at a UTF-16 offset.
/// Returns 0=Whitespace, 1=Word, 2=Punctuation, 3=LineEnding
int charClassAt({required RopeInstance instance, required int offsetUtf16}) =>
    RustLib.instance.api
        .crateApiCharClassAt(instance: instance, offsetUtf16: offsetUtf16);

int findWordBoundary(
        {required RopeInstance instance,
        required int offsetUtf16,
        required bool forward}) =>
    RustLib.instance.api.crateApiFindWordBoundary(
        instance: instance, offsetUtf16: offsetUtf16, forward: forward);

int utf16ToByteOffset(
        {required RopeInstance instance, required int offsetUtf16}) =>
    RustLib.instance.api.crateApiUtf16ToByteOffset(
        instance: instance, offsetUtf16: offsetUtf16);

int byteToUtf16OffsetPub(
        {required RopeInstance instance, required int byteOffset}) =>
    RustLib.instance.api.crateApiByteToUtf16OffsetPub(
        instance: instance, byteOffset: byteOffset);

int getLineStartByteOffset(
        {required RopeInstance instance, required int lineIndex}) =>
    RustLib.instance.api.crateApiGetLineStartByteOffset(
        instance: instance, lineIndex: lineIndex);

int lineColumnToByteOffset(
        {required RopeInstance instance,
        required int line,
        required int columnUtf16}) =>
    RustLib.instance.api.crateApiLineColumnToByteOffset(
        instance: instance, line: line, columnUtf16: columnUtf16);

List<int> byteOffsetToLineColumn(
        {required RopeInstance instance, required int byteOffset}) =>
    RustLib.instance.api.crateApiByteOffsetToLineColumn(
        instance: instance, byteOffset: byteOffset);

String reversedCharsAt(
        {required RopeInstance instance,
        required int offsetUtf16,
        required int maxChars}) =>
    RustLib.instance.api.crateApiReversedCharsAt(
        instance: instance, offsetUtf16: offsetUtf16, maxChars: maxChars);

String reversedTextInRange(
        {required RopeInstance instance,
        required int startUtf16,
        required int endUtf16}) =>
    RustLib.instance.api.crateApiReversedTextInRange(
        instance: instance, startUtf16: startUtf16, endUtf16: endUtf16);

int prevLineStart({required RopeInstance instance, required int offsetUtf16}) =>
    RustLib.instance.api
        .crateApiPrevLineStart(instance: instance, offsetUtf16: offsetUtf16);

int nextLineStart({required RopeInstance instance, required int offsetUtf16}) =>
    RustLib.instance.api
        .crateApiNextLineStart(instance: instance, offsetUtf16: offsetUtf16);

/// Get line indentation info for a contiguous range of lines.
/// More efficient than calling getLineIndentation in a loop.
List<LineIndentInfo> getLineIndentsRange(
        {required RopeInstance instance,
        required int startLine,
        required int endLine}) =>
    RustLib.instance.api.crateApiGetLineIndentsRange(
        instance: instance, startLine: startLine, endLine: endLine);

List<LineIndentInfo> getReversedLineIndentsRange(
        {required RopeInstance instance,
        required int startLine,
        required int endLine}) =>
    RustLib.instance.api.crateApiGetReversedLineIndentsRange(
        instance: instance, startLine: startLine, endLine: endLine);

/// Enhanced search with whole word matching.
/// Returns UTF-16 offsets as pairs [start, end, start, end, ...].
List<int> searchWholeWord(
        {required RopeInstance instance,
        required String pattern,
        required bool caseSensitive,
        required bool wholeWord}) =>
    RustLib.instance.api.crateApiSearchWholeWord(
        instance: instance,
        pattern: pattern,
        caseSensitive: caseSensitive,
        wholeWord: wholeWord);

/// Search with include/exclude path patterns.
/// This version accepts line ranges and can skip certain regions.
List<int> searchWithRanges(
        {required RopeInstance instance,
        required String pattern,
        required bool caseSensitive,
        required bool isRegex,
        required bool wholeWord,
        List<(int, int)>? includeLines,
        List<(int, int)>? excludeLines}) =>
    RustLib.instance.api.crateApiSearchWithRanges(
        instance: instance,
        pattern: pattern,
        caseSensitive: caseSensitive,
        isRegex: isRegex,
        wholeWord: wholeWord,
        includeLines: includeLines,
        excludeLines: excludeLines);

DocumentTextSummary getTextSummary({required RopeInstance instance}) =>
    RustLib.instance.api.crateApiGetTextSummary(instance: instance);

List<int> offsetToPoint(
        {required RopeInstance instance, required int offsetUtf16}) =>
    RustLib.instance.api
        .crateApiOffsetToPoint(instance: instance, offsetUtf16: offsetUtf16);

int pointToOffset(
        {required RopeInstance instance,
        required int row,
        required int columnBytes}) =>
    RustLib.instance.api.crateApiPointToOffset(
        instance: instance, row: row, columnBytes: columnBytes);

List<int> clipPoint(
        {required RopeInstance instance,
        required int row,
        required int columnBytes,
        required int bias}) =>
    RustLib.instance.api.crateApiClipPoint(
        instance: instance, row: row, columnBytes: columnBytes, bias: bias);

/// Combined replace operation that returns all edit context in a single FFI call.
///
/// This is the HIGH-PERFORMANCE replacement for the pattern:
///   deletedText = rope.substring(start, end);  // FFI call 1 - EXPENSIVE
///   rope.replace(start, end, text);            // FFI call 2
///   line = rope.getLineAtOffset(newCursor);    // FFI call 3 - EXPENSIVE
///
/// Now becomes:
///   result = rope.replaceAndCapture(start, end, text);  // Single FFI call
///
/// Performance impact: Eliminates ~82% of CPU time spent in FFI calls during typing.
EditResult replaceAndCapture(
        {required RopeInstance instance,
        required int startUtf16,
        required int endUtf16,
        required String text}) =>
    RustLib.instance.api.crateApiReplaceAndCapture(
        instance: instance,
        startUtf16: startUtf16,
        endUtf16: endUtf16,
        text: text);

/// Get complete cursor context in a single FFI call.
/// Replaces multiple calls to getLineAtOffset(), getLineStartOffset(), etc.
///
/// This is the HIGH-PERFORMANCE replacement for the pattern:
///   line = rope.getLineAtOffset(offset);       // FFI call 1
///   lineStart = rope.getLineStartOffset(line); // FFI call 2
///   column = offset - lineStart;               // computation
///
/// Now becomes:
///   ctx = rope.getCursorContext(offset);       // Single FFI call
CursorContext getCursorContext(
        {required RopeInstance instance, required int offsetUtf16}) =>
    RustLib.instance.api
        .crateApiGetCursorContext(instance: instance, offsetUtf16: offsetUtf16);

/// Get or update the IME projection window.
///
/// This is a SMART API that:
/// 1. Checks if the cursor is still within the cached window
/// 2. Only extracts text if the window needs to shift
/// 3. Returns an empty string if the cached window is still valid
///
/// Parameters:
/// - caret_offset: Current cursor position in UTF-16
/// - selection_base: Selection start in UTF-16
/// - selection_extent: Selection end in UTF-16
/// - max_window_size: Maximum window size (typically 4000 chars)
/// - cached_window_start: The start of the previously cached window
/// - cached_window_end: The end of the previously cached window
///
/// Returns ImeProjection with window_changed=false if cache is still valid.
ImeProjection getImeProjection(
        {required RopeInstance instance,
        required int caretOffset,
        required int selectionBase,
        required int selectionExtent,
        required int maxWindowSize,
        required int cachedWindowStart,
        required int cachedWindowEnd}) =>
    RustLib.instance.api.crateApiGetImeProjection(
        instance: instance,
        caretOffset: caretOffset,
        selectionBase: selectionBase,
        selectionExtent: selectionExtent,
        maxWindowSize: maxWindowSize,
        cachedWindowStart: cachedWindowStart,
        cachedWindowEnd: cachedWindowEnd);

bool isImeWindowValid(
        {required RopeInstance instance,
        required int caretOffset,
        required int maxWindowSize,
        required int cachedWindowStart,
        required int cachedWindowEnd}) =>
    RustLib.instance.api.crateApiIsImeWindowValid(
        instance: instance,
        caretOffset: caretOffset,
        maxWindowSize: maxWindowSize,
        cachedWindowStart: cachedWindowStart,
        cachedWindowEnd: cachedWindowEnd);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RopeInstance>>
abstract class RopeInstance implements RustOpaqueInterface {}

/// Cursor context returned by get_cursor_context.
/// Provides all information needed for cursor positioning in a single FFI call.
class CursorContext {
  /// The 0-based line index.
  final int line;

  /// The column within the line in UTF-16 code units.
  final int column;

  /// UTF-16 offset where the current line starts.
  final int lineStartOffset;

  /// UTF-16 offset where the current line ends (before newline).
  final int lineEndOffset;

  /// Length of the current line in UTF-16 code units (excluding newline).
  final int lineLength;

  /// Total number of lines in the document.
  final int totalLines;

  /// Total document length in UTF-16 code units.
  final int totalLength;

  const CursorContext({
    required this.line,
    required this.column,
    required this.lineStartOffset,
    required this.lineEndOffset,
    required this.lineLength,
    required this.totalLines,
    required this.totalLength,
  });

  @override
  int get hashCode =>
      line.hashCode ^
      column.hashCode ^
      lineStartOffset.hashCode ^
      lineEndOffset.hashCode ^
      lineLength.hashCode ^
      totalLines.hashCode ^
      totalLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CursorContext &&
          runtimeType == other.runtimeType &&
          line == other.line &&
          column == other.column &&
          lineStartOffset == other.lineStartOffset &&
          lineEndOffset == other.lineEndOffset &&
          lineLength == other.lineLength &&
          totalLines == other.totalLines &&
          totalLength == other.totalLength;
}

/// Comprehensive text metrics matching Zed's TextSummary.
/// Note: renamed to avoid collision with zed_rope::TextSummary.
class DocumentTextSummary {
  final int len;
  final int chars;
  final int lenUtf16;
  final int lines;
  final int lastLineColumn;
  final int firstLineChars;
  final int lastLineChars;
  final int lastLineLenUtf16;
  final int longestRow;
  final int longestRowChars;

  const DocumentTextSummary({
    required this.len,
    required this.chars,
    required this.lenUtf16,
    required this.lines,
    required this.lastLineColumn,
    required this.firstLineChars,
    required this.lastLineChars,
    required this.lastLineLenUtf16,
    required this.longestRow,
    required this.longestRowChars,
  });

  @override
  int get hashCode =>
      len.hashCode ^
      chars.hashCode ^
      lenUtf16.hashCode ^
      lines.hashCode ^
      lastLineColumn.hashCode ^
      firstLineChars.hashCode ^
      lastLineChars.hashCode ^
      lastLineLenUtf16.hashCode ^
      longestRow.hashCode ^
      longestRowChars.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentTextSummary &&
          runtimeType == other.runtimeType &&
          len == other.len &&
          chars == other.chars &&
          lenUtf16 == other.lenUtf16 &&
          lines == other.lines &&
          lastLineColumn == other.lastLineColumn &&
          firstLineChars == other.firstLineChars &&
          lastLineChars == other.lastLineChars &&
          lastLineLenUtf16 == other.lastLineLenUtf16 &&
          longestRow == other.longestRow &&
          longestRowChars == other.longestRowChars;
}

/// Result of a replace operation with all context needed for undo/redo and UI updates.
/// This eliminates the need for separate FFI calls to get deleted text, cursor position, etc.
class EditResult {
  /// The text that was deleted (for undo recording).
  /// This is computed on the Rust side to avoid a separate substring() call.
  final String deletedText;

  /// The new document length in UTF-16 code units.
  final int newLength;

  /// The new cursor position in UTF-16 code units (start + replacement.len()).
  final int newCursor;

  /// The line number where the cursor now sits.
  final int cursorLine;

  /// The column within the line (in UTF-16 code units).
  final int cursorColumn;

  /// Start offset of the current line (for IME projection).
  final int lineStartOffset;

  /// Length of the current line (excluding newline).
  final int lineLength;

  /// Whether the edit changed the number of lines in the document.
  final bool lineCountChanged;

  /// The new line count.
  final int newLineCount;

  const EditResult({
    required this.deletedText,
    required this.newLength,
    required this.newCursor,
    required this.cursorLine,
    required this.cursorColumn,
    required this.lineStartOffset,
    required this.lineLength,
    required this.lineCountChanged,
    required this.newLineCount,
  });

  @override
  int get hashCode =>
      deletedText.hashCode ^
      newLength.hashCode ^
      newCursor.hashCode ^
      cursorLine.hashCode ^
      cursorColumn.hashCode ^
      lineStartOffset.hashCode ^
      lineLength.hashCode ^
      lineCountChanged.hashCode ^
      newLineCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditResult &&
          runtimeType == other.runtimeType &&
          deletedText == other.deletedText &&
          newLength == other.newLength &&
          newCursor == other.newCursor &&
          cursorLine == other.cursorLine &&
          cursorColumn == other.cursorColumn &&
          lineStartOffset == other.lineStartOffset &&
          lineLength == other.lineLength &&
          lineCountChanged == other.lineCountChanged &&
          newLineCount == other.newLineCount;
}

/// IME projection window state.
class ImeProjection {
  /// Whether a new window was computed (false means use cached).
  final bool windowChanged;

  /// Start offset of the window in the document (UTF-16).
  final int windowStart;

  /// The text content of the window (empty if window_changed is false).
  final String text;

  /// Selection base offset relative to window_start.
  final int selectionBase;

  /// Selection extent offset relative to window_start.
  final int selectionExtent;

  const ImeProjection({
    required this.windowChanged,
    required this.windowStart,
    required this.text,
    required this.selectionBase,
    required this.selectionExtent,
  });

  @override
  int get hashCode =>
      windowChanged.hashCode ^
      windowStart.hashCode ^
      text.hashCode ^
      selectionBase.hashCode ^
      selectionExtent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImeProjection &&
          runtimeType == other.runtimeType &&
          windowChanged == other.windowChanged &&
          windowStart == other.windowStart &&
          text == other.text &&
          selectionBase == other.selectionBase &&
          selectionExtent == other.selectionExtent;
}

/// Information about the indentation style detected in a document.
class IndentInfo {
  /// Whether the document primarily uses tabs for indentation.
  final bool usesTabs;

  /// The detected number of spaces per indent level (2, 4, 8, etc.).
  /// Only meaningful if uses_tabs is false.
  final int spacesPerIndent;

  /// Whether the document has mixed indentation styles.
  final bool mixed;

  const IndentInfo({
    required this.usesTabs,
    required this.spacesPerIndent,
    required this.mixed,
  });

  @override
  int get hashCode =>
      usesTabs.hashCode ^ spacesPerIndent.hashCode ^ mixed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndentInfo &&
          runtimeType == other.runtimeType &&
          usesTabs == other.usesTabs &&
          spacesPerIndent == other.spacesPerIndent &&
          mixed == other.mixed;
}

/// Line indent information.
class LineIndentInfo {
  /// Number of leading tab characters.
  final int tabs;

  /// Number of leading space characters.
  final int spaces;

  /// Whether the line is blank (whitespace only).
  final bool lineBlank;

  const LineIndentInfo({
    required this.tabs,
    required this.spaces,
    required this.lineBlank,
  });

  @override
  int get hashCode => tabs.hashCode ^ spaces.hashCode ^ lineBlank.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineIndentInfo &&
          runtimeType == other.runtimeType &&
          tabs == other.tabs &&
          spaces == other.spaces &&
          lineBlank == other.lineBlank;
}

/// Minimap density data for a single line.
/// Avoids serializing full line strings just to measure whitespace/content.
class MinimapLineDensity {
  /// Number of leading whitespace characters (spaces/tabs).
  final int leadingWhitespace;

  /// Length of non-whitespace content (excluding leading/trailing whitespace).
  final int contentLength;

  /// Whether the line is empty or whitespace-only.
  final bool isEmpty;

  const MinimapLineDensity({
    required this.leadingWhitespace,
    required this.contentLength,
    required this.isEmpty,
  });

  @override
  int get hashCode =>
      leadingWhitespace.hashCode ^ contentLength.hashCode ^ isEmpty.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MinimapLineDensity &&
          runtimeType == other.runtimeType &&
          leadingWhitespace == other.leadingWhitespace &&
          contentLength == other.contentLength &&
          isEmpty == other.isEmpty;
}

/// Metrics returned in a single FFI call to minimize cross-language traffic.
class RopeMetrics {
  final int byteLen;
  final int charLen;
  final int utf16Len;
  final int lineCount;
  final int maxLineUtf16Len;

  const RopeMetrics({
    required this.byteLen,
    required this.charLen,
    required this.utf16Len,
    required this.lineCount,
    required this.maxLineUtf16Len,
  });

  @override
  int get hashCode =>
      byteLen.hashCode ^
      charLen.hashCode ^
      utf16Len.hashCode ^
      lineCount.hashCode ^
      maxLineUtf16Len.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RopeMetrics &&
          runtimeType == other.runtimeType &&
          byteLen == other.byteLen &&
          charLen == other.charLen &&
          utf16Len == other.utf16Len &&
          lineCount == other.lineCount &&
          maxLineUtf16Len == other.maxLineUtf16Len;
}
