// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_RopeInstancePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstancePtr;

  @protected
  RopeInstance
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          dynamic raw);

  @protected
  RopeInstance
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_usize(dynamic raw);

  @protected
  RopeInstance
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CursorContext dco_decode_cursor_context(dynamic raw);

  @protected
  DocumentTextSummary dco_decode_document_text_summary(dynamic raw);

  @protected
  EditResult dco_decode_edit_result(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImeProjection dco_decode_ime_projection(dynamic raw);

  @protected
  IndentInfo dco_decode_indent_info(dynamic raw);

  @protected
  LineIndentInfo dco_decode_line_indent_info(dynamic raw);

  @protected
  List<int> dco_decode_list_CastedPrimitive_usize(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<LineIndentInfo> dco_decode_list_line_indent_info(dynamic raw);

  @protected
  List<MinimapLineDensity> dco_decode_list_minimap_line_density(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(int, int)>
      dco_decode_list_record_casted_primitive_usize_casted_primitive_usize(
          dynamic raw);

  @protected
  MinimapLineDensity dco_decode_minimap_line_density(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_usize(dynamic raw);

  @protected
  List<(int, int)>?
      dco_decode_opt_list_record_casted_primitive_usize_casted_primitive_usize(
          dynamic raw);

  @protected
  (int, int) dco_decode_record_casted_primitive_usize_casted_primitive_usize(
      dynamic raw);

  @protected
  RopeMetrics dco_decode_rope_metrics(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  RopeInstance
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          SseDeserializer deserializer);

  @protected
  RopeInstance
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_usize(SseDeserializer deserializer);

  @protected
  RopeInstance
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CursorContext sse_decode_cursor_context(SseDeserializer deserializer);

  @protected
  DocumentTextSummary sse_decode_document_text_summary(
      SseDeserializer deserializer);

  @protected
  EditResult sse_decode_edit_result(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImeProjection sse_decode_ime_projection(SseDeserializer deserializer);

  @protected
  IndentInfo sse_decode_indent_info(SseDeserializer deserializer);

  @protected
  LineIndentInfo sse_decode_line_indent_info(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_CastedPrimitive_usize(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<LineIndentInfo> sse_decode_list_line_indent_info(
      SseDeserializer deserializer);

  @protected
  List<MinimapLineDensity> sse_decode_list_minimap_line_density(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(int, int)>
      sse_decode_list_record_casted_primitive_usize_casted_primitive_usize(
          SseDeserializer deserializer);

  @protected
  MinimapLineDensity sse_decode_minimap_line_density(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_usize(SseDeserializer deserializer);

  @protected
  List<(int, int)>?
      sse_decode_opt_list_record_casted_primitive_usize_casted_primitive_usize(
          SseDeserializer deserializer);

  @protected
  (int, int) sse_decode_record_casted_primitive_usize_casted_primitive_usize(
      SseDeserializer deserializer);

  @protected
  RopeMetrics sse_decode_rope_metrics(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          RopeInstance self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          RopeInstance self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_usize(int self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          RopeInstance self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_cursor_context(CursorContext self, SseSerializer serializer);

  @protected
  void sse_encode_document_text_summary(
      DocumentTextSummary self, SseSerializer serializer);

  @protected
  void sse_encode_edit_result(EditResult self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_ime_projection(ImeProjection self, SseSerializer serializer);

  @protected
  void sse_encode_indent_info(IndentInfo self, SseSerializer serializer);

  @protected
  void sse_encode_line_indent_info(
      LineIndentInfo self, SseSerializer serializer);

  @protected
  void sse_encode_list_CastedPrimitive_usize(
      List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_line_indent_info(
      List<LineIndentInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_minimap_line_density(
      List<MinimapLineDensity> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_casted_primitive_usize_casted_primitive_usize(
      List<(int, int)> self, SseSerializer serializer);

  @protected
  void sse_encode_minimap_line_density(
      MinimapLineDensity self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_usize(
      int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_record_casted_primitive_usize_casted_primitive_usize(
      List<(int, int)>? self, SseSerializer serializer);

  @protected
  void sse_encode_record_casted_primitive_usize_casted_primitive_usize(
      (int, int) self, SseSerializer serializer);

  @protected
  void sse_encode_rope_metrics(RopeMetrics self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstancePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_rope_editor_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstancePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstancePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_rope_editor_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstancePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
