// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -438618491;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rope_editor',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  List<int> crateApiByteOffsetToLineColumn(
      {required RopeInstance instance, required int byteOffset});

  int crateApiByteToUtf16OffsetPub(
      {required RopeInstance instance, required int byteOffset});

  int crateApiCharClassAt(
      {required RopeInstance instance, required int offsetUtf16});

  List<int> crateApiClipPoint(
      {required RopeInstance instance,
      required int row,
      required int columnBytes,
      required int bias});

  RopeInstance crateApiCreateRopeInstance({required String text});

  Future<RopeInstance> crateApiCreateRopeInstanceAsync({required String text});

  Future<RopeInstance> crateApiCreateRopeInstanceFromFile(
      {required String path, int? maxChars});

  void crateApiDelete(
      {required RopeInstance instance,
      required int startUtf16,
      required int endUtf16});

  IndentInfo crateApiDetectIndentation({required RopeInstance instance});

  int crateApiFindWordBoundary(
      {required RopeInstance instance,
      required int offsetUtf16,
      required bool forward});

  int crateApiGetContentHash({required RopeInstance instance});

  CursorContext crateApiGetCursorContext(
      {required RopeInstance instance, required int offsetUtf16});

  ImeProjection crateApiGetImeProjection(
      {required RopeInstance instance,
      required int caretOffset,
      required int selectionBase,
      required int selectionExtent,
      required int maxWindowSize,
      required int cachedWindowStart,
      required int cachedWindowEnd});

  int crateApiGetLengthUtf16({required RopeInstance instance});

  int crateApiGetLineAtOffsetUtf16(
      {required RopeInstance instance, required int offsetUtf16});

  int crateApiGetLineCount({required RopeInstance instance});

  int crateApiGetLineIndentation(
      {required RopeInstance instance, required int lineIndex});

  List<LineIndentInfo> crateApiGetLineIndentsRange(
      {required RopeInstance instance,
      required int startLine,
      required int endLine});

  int crateApiGetLineStartByteOffset(
      {required RopeInstance instance, required int lineIndex});

  int crateApiGetLineStartOffsetUtf16(
      {required RopeInstance instance, required int lineIndex});

  List<int> crateApiGetLineStartOffsetsBatch(
      {required RopeInstance instance,
      required int startLine,
      required int endLine});

  String crateApiGetLineText(
      {required RopeInstance instance, required int lineIndex});

  List<String> crateApiGetLinesTextBatch(
      {required RopeInstance instance, required List<int> lineIndices});

  String crateApiGetLinesTextRange(
      {required RopeInstance instance,
      required int startLine,
      required int endLine});

  RopeMetrics crateApiGetMetrics({required RopeInstance instance});

  List<MinimapLineDensity> crateApiGetMinimapDensityBatch(
      {required RopeInstance instance, required List<int> lineIndices});

  List<LineIndentInfo> crateApiGetReversedLineIndentsRange(
      {required RopeInstance instance,
      required int startLine,
      required int endLine});

  String crateApiGetText({required RopeInstance instance});

  Future<String> crateApiGetTextAsync({required RopeInstance instance});

  String crateApiGetTextChunk(
      {required RopeInstance instance,
      required int startUtf16,
      required int maxLength});

  String crateApiGetTextRange(
      {required RopeInstance instance,
      required int startUtf16,
      required int endUtf16});

  DocumentTextSummary crateApiGetTextSummary({required RopeInstance instance});

  void crateApiInsert(
      {required RopeInstance instance,
      required int offsetUtf16,
      required String text});

  bool crateApiIsImeWindowValid(
      {required RopeInstance instance,
      required int caretOffset,
      required int maxWindowSize,
      required int cachedWindowStart,
      required int cachedWindowEnd});

  int crateApiLineColumnToByteOffset(
      {required RopeInstance instance,
      required int line,
      required int columnUtf16});

  int crateApiNextLineStart(
      {required RopeInstance instance, required int offsetUtf16});

  List<int> crateApiOffsetToPoint(
      {required RopeInstance instance, required int offsetUtf16});

  int crateApiPointToOffset(
      {required RopeInstance instance,
      required int row,
      required int columnBytes});

  int crateApiPrevLineStart(
      {required RopeInstance instance, required int offsetUtf16});

  void crateApiReplace(
      {required RopeInstance instance,
      required int startUtf16,
      required int endUtf16,
      required String text});

  EditResult crateApiReplaceAndCapture(
      {required RopeInstance instance,
      required int startUtf16,
      required int endUtf16,
      required String text});

  String crateApiReversedCharsAt(
      {required RopeInstance instance,
      required int offsetUtf16,
      required int maxChars});

  String crateApiReversedTextInRange(
      {required RopeInstance instance,
      required int startUtf16,
      required int endUtf16});

  List<int> crateApiSearch(
      {required RopeInstance instance,
      required String pattern,
      required bool caseSensitive,
      required bool isRegex});

  List<int> crateApiSearchInRange(
      {required RopeInstance instance,
      required String pattern,
      required int startLine,
      required int endLine,
      required bool caseSensitive,
      required bool isRegex});

  List<int> crateApiSearchWholeWord(
      {required RopeInstance instance,
      required String pattern,
      required bool caseSensitive,
      required bool wholeWord});

  List<int> crateApiSearchWithRanges(
      {required RopeInstance instance,
      required String pattern,
      required bool caseSensitive,
      required bool isRegex,
      required bool wholeWord,
      List<(int, int)>? includeLines,
      List<(int, int)>? excludeLines});

  int crateApiUtf16ToByteOffset(
      {required RopeInstance instance, required int offsetUtf16});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_RopeInstance;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_RopeInstance;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RopeInstancePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  List<int> crateApiByteOffsetToLineColumn(
      {required RopeInstance instance, required int byteOffset}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(byteOffset, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiByteOffsetToLineColumnConstMeta,
      argValues: [instance, byteOffset],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiByteOffsetToLineColumnConstMeta =>
      const TaskConstMeta(
        debugName: "byte_offset_to_line_column",
        argNames: ["instance", "byteOffset"],
      );

  @override
  int crateApiByteToUtf16OffsetPub(
      {required RopeInstance instance, required int byteOffset}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(byteOffset, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiByteToUtf16OffsetPubConstMeta,
      argValues: [instance, byteOffset],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiByteToUtf16OffsetPubConstMeta =>
      const TaskConstMeta(
        debugName: "byte_to_utf16_offset_pub",
        argNames: ["instance", "byteOffset"],
      );

  @override
  int crateApiCharClassAt(
      {required RopeInstance instance, required int offsetUtf16}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(offsetUtf16, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_8,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCharClassAtConstMeta,
      argValues: [instance, offsetUtf16],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCharClassAtConstMeta => const TaskConstMeta(
        debugName: "char_class_at",
        argNames: ["instance", "offsetUtf16"],
      );

  @override
  List<int> crateApiClipPoint(
      {required RopeInstance instance,
      required int row,
      required int columnBytes,
      required int bias}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(row, serializer);
        sse_encode_CastedPrimitive_usize(columnBytes, serializer);
        sse_encode_u_8(bias, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiClipPointConstMeta,
      argValues: [instance, row, columnBytes, bias],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClipPointConstMeta => const TaskConstMeta(
        debugName: "clip_point",
        argNames: ["instance", "row", "columnBytes", "bias"],
      );

  @override
  RopeInstance crateApiCreateRopeInstance({required String text}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(text, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCreateRopeInstanceConstMeta,
      argValues: [text],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateRopeInstanceConstMeta => const TaskConstMeta(
        debugName: "create_rope_instance",
        argNames: ["text"],
      );

  @override
  Future<RopeInstance> crateApiCreateRopeInstanceAsync({required String text}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(text, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCreateRopeInstanceAsyncConstMeta,
      argValues: [text],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateRopeInstanceAsyncConstMeta =>
      const TaskConstMeta(
        debugName: "create_rope_instance_async",
        argNames: ["text"],
      );

  @override
  Future<RopeInstance> crateApiCreateRopeInstanceFromFile(
      {required String path, int? maxChars}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_opt_CastedPrimitive_usize(maxChars, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCreateRopeInstanceFromFileConstMeta,
      argValues: [path, maxChars],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateRopeInstanceFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "create_rope_instance_from_file",
        argNames: ["path", "maxChars"],
      );

  @override
  void crateApiDelete(
      {required RopeInstance instance,
      required int startUtf16,
      required int endUtf16}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(startUtf16, serializer);
        sse_encode_CastedPrimitive_usize(endUtf16, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDeleteConstMeta,
      argValues: [instance, startUtf16, endUtf16],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteConstMeta => const TaskConstMeta(
        debugName: "delete",
        argNames: ["instance", "startUtf16", "endUtf16"],
      );

  @override
  IndentInfo crateApiDetectIndentation({required RopeInstance instance}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_indent_info,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDetectIndentationConstMeta,
      argValues: [instance],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDetectIndentationConstMeta => const TaskConstMeta(
        debugName: "detect_indentation",
        argNames: ["instance"],
      );

  @override
  int crateApiFindWordBoundary(
      {required RopeInstance instance,
      required int offsetUtf16,
      required bool forward}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(offsetUtf16, serializer);
        sse_encode_bool(forward, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFindWordBoundaryConstMeta,
      argValues: [instance, offsetUtf16, forward],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFindWordBoundaryConstMeta => const TaskConstMeta(
        debugName: "find_word_boundary",
        argNames: ["instance", "offsetUtf16", "forward"],
      );

  @override
  int crateApiGetContentHash({required RopeInstance instance}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_CastedPrimitive_i_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetContentHashConstMeta,
      argValues: [instance],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetContentHashConstMeta => const TaskConstMeta(
        debugName: "get_content_hash",
        argNames: ["instance"],
      );

  @override
  CursorContext crateApiGetCursorContext(
      {required RopeInstance instance, required int offsetUtf16}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(offsetUtf16, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_cursor_context,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetCursorContextConstMeta,
      argValues: [instance, offsetUtf16],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetCursorContextConstMeta => const TaskConstMeta(
        debugName: "get_cursor_context",
        argNames: ["instance", "offsetUtf16"],
      );

  @override
  ImeProjection crateApiGetImeProjection(
      {required RopeInstance instance,
      required int caretOffset,
      required int selectionBase,
      required int selectionExtent,
      required int maxWindowSize,
      required int cachedWindowStart,
      required int cachedWindowEnd}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(caretOffset, serializer);
        sse_encode_CastedPrimitive_usize(selectionBase, serializer);
        sse_encode_CastedPrimitive_usize(selectionExtent, serializer);
        sse_encode_CastedPrimitive_usize(maxWindowSize, serializer);
        sse_encode_CastedPrimitive_usize(cachedWindowStart, serializer);
        sse_encode_CastedPrimitive_usize(cachedWindowEnd, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ime_projection,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetImeProjectionConstMeta,
      argValues: [
        instance,
        caretOffset,
        selectionBase,
        selectionExtent,
        maxWindowSize,
        cachedWindowStart,
        cachedWindowEnd
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetImeProjectionConstMeta => const TaskConstMeta(
        debugName: "get_ime_projection",
        argNames: [
          "instance",
          "caretOffset",
          "selectionBase",
          "selectionExtent",
          "maxWindowSize",
          "cachedWindowStart",
          "cachedWindowEnd"
        ],
      );

  @override
  int crateApiGetLengthUtf16({required RopeInstance instance}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetLengthUtf16ConstMeta,
      argValues: [instance],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetLengthUtf16ConstMeta => const TaskConstMeta(
        debugName: "get_length_utf16",
        argNames: ["instance"],
      );

  @override
  int crateApiGetLineAtOffsetUtf16(
      {required RopeInstance instance, required int offsetUtf16}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(offsetUtf16, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetLineAtOffsetUtf16ConstMeta,
      argValues: [instance, offsetUtf16],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetLineAtOffsetUtf16ConstMeta =>
      const TaskConstMeta(
        debugName: "get_line_at_offset_utf16",
        argNames: ["instance", "offsetUtf16"],
      );

  @override
  int crateApiGetLineCount({required RopeInstance instance}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetLineCountConstMeta,
      argValues: [instance],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetLineCountConstMeta => const TaskConstMeta(
        debugName: "get_line_count",
        argNames: ["instance"],
      );

  @override
  int crateApiGetLineIndentation(
      {required RopeInstance instance, required int lineIndex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(lineIndex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetLineIndentationConstMeta,
      argValues: [instance, lineIndex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetLineIndentationConstMeta => const TaskConstMeta(
        debugName: "get_line_indentation",
        argNames: ["instance", "lineIndex"],
      );

  @override
  List<LineIndentInfo> crateApiGetLineIndentsRange(
      {required RopeInstance instance,
      required int startLine,
      required int endLine}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(startLine, serializer);
        sse_encode_CastedPrimitive_usize(endLine, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_line_indent_info,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetLineIndentsRangeConstMeta,
      argValues: [instance, startLine, endLine],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetLineIndentsRangeConstMeta =>
      const TaskConstMeta(
        debugName: "get_line_indents_range",
        argNames: ["instance", "startLine", "endLine"],
      );

  @override
  int crateApiGetLineStartByteOffset(
      {required RopeInstance instance, required int lineIndex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(lineIndex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetLineStartByteOffsetConstMeta,
      argValues: [instance, lineIndex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetLineStartByteOffsetConstMeta =>
      const TaskConstMeta(
        debugName: "get_line_start_byte_offset",
        argNames: ["instance", "lineIndex"],
      );

  @override
  int crateApiGetLineStartOffsetUtf16(
      {required RopeInstance instance, required int lineIndex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(lineIndex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetLineStartOffsetUtf16ConstMeta,
      argValues: [instance, lineIndex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetLineStartOffsetUtf16ConstMeta =>
      const TaskConstMeta(
        debugName: "get_line_start_offset_utf16",
        argNames: ["instance", "lineIndex"],
      );

  @override
  List<int> crateApiGetLineStartOffsetsBatch(
      {required RopeInstance instance,
      required int startLine,
      required int endLine}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(startLine, serializer);
        sse_encode_CastedPrimitive_usize(endLine, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetLineStartOffsetsBatchConstMeta,
      argValues: [instance, startLine, endLine],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetLineStartOffsetsBatchConstMeta =>
      const TaskConstMeta(
        debugName: "get_line_start_offsets_batch",
        argNames: ["instance", "startLine", "endLine"],
      );

  @override
  String crateApiGetLineText(
      {required RopeInstance instance, required int lineIndex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(lineIndex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetLineTextConstMeta,
      argValues: [instance, lineIndex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetLineTextConstMeta => const TaskConstMeta(
        debugName: "get_line_text",
        argNames: ["instance", "lineIndex"],
      );

  @override
  List<String> crateApiGetLinesTextBatch(
      {required RopeInstance instance, required List<int> lineIndices}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_list_CastedPrimitive_usize(lineIndices, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetLinesTextBatchConstMeta,
      argValues: [instance, lineIndices],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetLinesTextBatchConstMeta => const TaskConstMeta(
        debugName: "get_lines_text_batch",
        argNames: ["instance", "lineIndices"],
      );

  @override
  String crateApiGetLinesTextRange(
      {required RopeInstance instance,
      required int startLine,
      required int endLine}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(startLine, serializer);
        sse_encode_CastedPrimitive_usize(endLine, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetLinesTextRangeConstMeta,
      argValues: [instance, startLine, endLine],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetLinesTextRangeConstMeta => const TaskConstMeta(
        debugName: "get_lines_text_range",
        argNames: ["instance", "startLine", "endLine"],
      );

  @override
  RopeMetrics crateApiGetMetrics({required RopeInstance instance}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_rope_metrics,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetMetricsConstMeta,
      argValues: [instance],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetMetricsConstMeta => const TaskConstMeta(
        debugName: "get_metrics",
        argNames: ["instance"],
      );

  @override
  List<MinimapLineDensity> crateApiGetMinimapDensityBatch(
      {required RopeInstance instance, required List<int> lineIndices}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_list_CastedPrimitive_usize(lineIndices, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_minimap_line_density,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetMinimapDensityBatchConstMeta,
      argValues: [instance, lineIndices],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetMinimapDensityBatchConstMeta =>
      const TaskConstMeta(
        debugName: "get_minimap_density_batch",
        argNames: ["instance", "lineIndices"],
      );

  @override
  List<LineIndentInfo> crateApiGetReversedLineIndentsRange(
      {required RopeInstance instance,
      required int startLine,
      required int endLine}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(startLine, serializer);
        sse_encode_CastedPrimitive_usize(endLine, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_line_indent_info,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetReversedLineIndentsRangeConstMeta,
      argValues: [instance, startLine, endLine],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetReversedLineIndentsRangeConstMeta =>
      const TaskConstMeta(
        debugName: "get_reversed_line_indents_range",
        argNames: ["instance", "startLine", "endLine"],
      );

  @override
  String crateApiGetText({required RopeInstance instance}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetTextConstMeta,
      argValues: [instance],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetTextConstMeta => const TaskConstMeta(
        debugName: "get_text",
        argNames: ["instance"],
      );

  @override
  Future<String> crateApiGetTextAsync({required RopeInstance instance}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetTextAsyncConstMeta,
      argValues: [instance],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetTextAsyncConstMeta => const TaskConstMeta(
        debugName: "get_text_async",
        argNames: ["instance"],
      );

  @override
  String crateApiGetTextChunk(
      {required RopeInstance instance,
      required int startUtf16,
      required int maxLength}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(startUtf16, serializer);
        sse_encode_CastedPrimitive_usize(maxLength, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetTextChunkConstMeta,
      argValues: [instance, startUtf16, maxLength],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetTextChunkConstMeta => const TaskConstMeta(
        debugName: "get_text_chunk",
        argNames: ["instance", "startUtf16", "maxLength"],
      );

  @override
  String crateApiGetTextRange(
      {required RopeInstance instance,
      required int startUtf16,
      required int endUtf16}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(startUtf16, serializer);
        sse_encode_CastedPrimitive_usize(endUtf16, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetTextRangeConstMeta,
      argValues: [instance, startUtf16, endUtf16],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetTextRangeConstMeta => const TaskConstMeta(
        debugName: "get_text_range",
        argNames: ["instance", "startUtf16", "endUtf16"],
      );

  @override
  DocumentTextSummary crateApiGetTextSummary({required RopeInstance instance}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_document_text_summary,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetTextSummaryConstMeta,
      argValues: [instance],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetTextSummaryConstMeta => const TaskConstMeta(
        debugName: "get_text_summary",
        argNames: ["instance"],
      );

  @override
  void crateApiInsert(
      {required RopeInstance instance,
      required int offsetUtf16,
      required String text}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(offsetUtf16, serializer);
        sse_encode_String(text, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInsertConstMeta,
      argValues: [instance, offsetUtf16, text],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInsertConstMeta => const TaskConstMeta(
        debugName: "insert",
        argNames: ["instance", "offsetUtf16", "text"],
      );

  @override
  bool crateApiIsImeWindowValid(
      {required RopeInstance instance,
      required int caretOffset,
      required int maxWindowSize,
      required int cachedWindowStart,
      required int cachedWindowEnd}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(caretOffset, serializer);
        sse_encode_CastedPrimitive_usize(maxWindowSize, serializer);
        sse_encode_CastedPrimitive_usize(cachedWindowStart, serializer);
        sse_encode_CastedPrimitive_usize(cachedWindowEnd, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiIsImeWindowValidConstMeta,
      argValues: [
        instance,
        caretOffset,
        maxWindowSize,
        cachedWindowStart,
        cachedWindowEnd
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIsImeWindowValidConstMeta => const TaskConstMeta(
        debugName: "is_ime_window_valid",
        argNames: [
          "instance",
          "caretOffset",
          "maxWindowSize",
          "cachedWindowStart",
          "cachedWindowEnd"
        ],
      );

  @override
  int crateApiLineColumnToByteOffset(
      {required RopeInstance instance,
      required int line,
      required int columnUtf16}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(line, serializer);
        sse_encode_CastedPrimitive_usize(columnUtf16, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLineColumnToByteOffsetConstMeta,
      argValues: [instance, line, columnUtf16],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLineColumnToByteOffsetConstMeta =>
      const TaskConstMeta(
        debugName: "line_column_to_byte_offset",
        argNames: ["instance", "line", "columnUtf16"],
      );

  @override
  int crateApiNextLineStart(
      {required RopeInstance instance, required int offsetUtf16}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(offsetUtf16, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiNextLineStartConstMeta,
      argValues: [instance, offsetUtf16],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNextLineStartConstMeta => const TaskConstMeta(
        debugName: "next_line_start",
        argNames: ["instance", "offsetUtf16"],
      );

  @override
  List<int> crateApiOffsetToPoint(
      {required RopeInstance instance, required int offsetUtf16}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(offsetUtf16, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiOffsetToPointConstMeta,
      argValues: [instance, offsetUtf16],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOffsetToPointConstMeta => const TaskConstMeta(
        debugName: "offset_to_point",
        argNames: ["instance", "offsetUtf16"],
      );

  @override
  int crateApiPointToOffset(
      {required RopeInstance instance,
      required int row,
      required int columnBytes}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(row, serializer);
        sse_encode_CastedPrimitive_usize(columnBytes, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPointToOffsetConstMeta,
      argValues: [instance, row, columnBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPointToOffsetConstMeta => const TaskConstMeta(
        debugName: "point_to_offset",
        argNames: ["instance", "row", "columnBytes"],
      );

  @override
  int crateApiPrevLineStart(
      {required RopeInstance instance, required int offsetUtf16}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(offsetUtf16, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 39)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPrevLineStartConstMeta,
      argValues: [instance, offsetUtf16],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPrevLineStartConstMeta => const TaskConstMeta(
        debugName: "prev_line_start",
        argNames: ["instance", "offsetUtf16"],
      );

  @override
  void crateApiReplace(
      {required RopeInstance instance,
      required int startUtf16,
      required int endUtf16,
      required String text}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(startUtf16, serializer);
        sse_encode_CastedPrimitive_usize(endUtf16, serializer);
        sse_encode_String(text, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiReplaceConstMeta,
      argValues: [instance, startUtf16, endUtf16, text],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReplaceConstMeta => const TaskConstMeta(
        debugName: "replace",
        argNames: ["instance", "startUtf16", "endUtf16", "text"],
      );

  @override
  EditResult crateApiReplaceAndCapture(
      {required RopeInstance instance,
      required int startUtf16,
      required int endUtf16,
      required String text}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(startUtf16, serializer);
        sse_encode_CastedPrimitive_usize(endUtf16, serializer);
        sse_encode_String(text, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 41)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_edit_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiReplaceAndCaptureConstMeta,
      argValues: [instance, startUtf16, endUtf16, text],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReplaceAndCaptureConstMeta => const TaskConstMeta(
        debugName: "replace_and_capture",
        argNames: ["instance", "startUtf16", "endUtf16", "text"],
      );

  @override
  String crateApiReversedCharsAt(
      {required RopeInstance instance,
      required int offsetUtf16,
      required int maxChars}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(offsetUtf16, serializer);
        sse_encode_CastedPrimitive_usize(maxChars, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 42)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiReversedCharsAtConstMeta,
      argValues: [instance, offsetUtf16, maxChars],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReversedCharsAtConstMeta => const TaskConstMeta(
        debugName: "reversed_chars_at",
        argNames: ["instance", "offsetUtf16", "maxChars"],
      );

  @override
  String crateApiReversedTextInRange(
      {required RopeInstance instance,
      required int startUtf16,
      required int endUtf16}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(startUtf16, serializer);
        sse_encode_CastedPrimitive_usize(endUtf16, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 43)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiReversedTextInRangeConstMeta,
      argValues: [instance, startUtf16, endUtf16],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReversedTextInRangeConstMeta =>
      const TaskConstMeta(
        debugName: "reversed_text_in_range",
        argNames: ["instance", "startUtf16", "endUtf16"],
      );

  @override
  List<int> crateApiSearch(
      {required RopeInstance instance,
      required String pattern,
      required bool caseSensitive,
      required bool isRegex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_String(pattern, serializer);
        sse_encode_bool(caseSensitive, serializer);
        sse_encode_bool(isRegex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 44)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSearchConstMeta,
      argValues: [instance, pattern, caseSensitive, isRegex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSearchConstMeta => const TaskConstMeta(
        debugName: "search",
        argNames: ["instance", "pattern", "caseSensitive", "isRegex"],
      );

  @override
  List<int> crateApiSearchInRange(
      {required RopeInstance instance,
      required String pattern,
      required int startLine,
      required int endLine,
      required bool caseSensitive,
      required bool isRegex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_String(pattern, serializer);
        sse_encode_CastedPrimitive_usize(startLine, serializer);
        sse_encode_CastedPrimitive_usize(endLine, serializer);
        sse_encode_bool(caseSensitive, serializer);
        sse_encode_bool(isRegex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 45)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSearchInRangeConstMeta,
      argValues: [
        instance,
        pattern,
        startLine,
        endLine,
        caseSensitive,
        isRegex
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSearchInRangeConstMeta => const TaskConstMeta(
        debugName: "search_in_range",
        argNames: [
          "instance",
          "pattern",
          "startLine",
          "endLine",
          "caseSensitive",
          "isRegex"
        ],
      );

  @override
  List<int> crateApiSearchWholeWord(
      {required RopeInstance instance,
      required String pattern,
      required bool caseSensitive,
      required bool wholeWord}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_String(pattern, serializer);
        sse_encode_bool(caseSensitive, serializer);
        sse_encode_bool(wholeWord, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 46)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSearchWholeWordConstMeta,
      argValues: [instance, pattern, caseSensitive, wholeWord],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSearchWholeWordConstMeta => const TaskConstMeta(
        debugName: "search_whole_word",
        argNames: ["instance", "pattern", "caseSensitive", "wholeWord"],
      );

  @override
  List<int> crateApiSearchWithRanges(
      {required RopeInstance instance,
      required String pattern,
      required bool caseSensitive,
      required bool isRegex,
      required bool wholeWord,
      List<(int, int)>? includeLines,
      List<(int, int)>? excludeLines}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_String(pattern, serializer);
        sse_encode_bool(caseSensitive, serializer);
        sse_encode_bool(isRegex, serializer);
        sse_encode_bool(wholeWord, serializer);
        sse_encode_opt_list_record_casted_primitive_usize_casted_primitive_usize(
            includeLines, serializer);
        sse_encode_opt_list_record_casted_primitive_usize_casted_primitive_usize(
            excludeLines, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 47)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSearchWithRangesConstMeta,
      argValues: [
        instance,
        pattern,
        caseSensitive,
        isRegex,
        wholeWord,
        includeLines,
        excludeLines
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSearchWithRangesConstMeta => const TaskConstMeta(
        debugName: "search_with_ranges",
        argNames: [
          "instance",
          "pattern",
          "caseSensitive",
          "isRegex",
          "wholeWord",
          "includeLines",
          "excludeLines"
        ],
      );

  @override
  int crateApiUtf16ToByteOffset(
      {required RopeInstance instance, required int offsetUtf16}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
            instance, serializer);
        sse_encode_CastedPrimitive_usize(offsetUtf16, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 48)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_CastedPrimitive_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiUtf16ToByteOffsetConstMeta,
      argValues: [instance, offsetUtf16],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUtf16ToByteOffsetConstMeta => const TaskConstMeta(
        debugName: "utf16_to_byte_offset",
        argNames: ["instance", "offsetUtf16"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_RopeInstance => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_RopeInstance => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance;

  @protected
  RopeInstance
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RopeInstanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RopeInstance
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RopeInstanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
        'Not implemented in this codec, please use the other one');
  }

  @protected
  int dco_decode_CastedPrimitive_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
        'Not implemented in this codec, please use the other one');
  }

  @protected
  RopeInstance
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RopeInstanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CursorContext dco_decode_cursor_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return CursorContext(
      line: dco_decode_CastedPrimitive_usize(arr[0]),
      column: dco_decode_CastedPrimitive_usize(arr[1]),
      lineStartOffset: dco_decode_CastedPrimitive_usize(arr[2]),
      lineEndOffset: dco_decode_CastedPrimitive_usize(arr[3]),
      lineLength: dco_decode_CastedPrimitive_usize(arr[4]),
      totalLines: dco_decode_CastedPrimitive_usize(arr[5]),
      totalLength: dco_decode_CastedPrimitive_usize(arr[6]),
    );
  }

  @protected
  DocumentTextSummary dco_decode_document_text_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return DocumentTextSummary(
      len: dco_decode_CastedPrimitive_usize(arr[0]),
      chars: dco_decode_CastedPrimitive_usize(arr[1]),
      lenUtf16: dco_decode_CastedPrimitive_usize(arr[2]),
      lines: dco_decode_CastedPrimitive_usize(arr[3]),
      lastLineColumn: dco_decode_CastedPrimitive_usize(arr[4]),
      firstLineChars: dco_decode_CastedPrimitive_usize(arr[5]),
      lastLineChars: dco_decode_CastedPrimitive_usize(arr[6]),
      lastLineLenUtf16: dco_decode_CastedPrimitive_usize(arr[7]),
      longestRow: dco_decode_CastedPrimitive_usize(arr[8]),
      longestRowChars: dco_decode_CastedPrimitive_usize(arr[9]),
    );
  }

  @protected
  EditResult dco_decode_edit_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return EditResult(
      deletedText: dco_decode_String(arr[0]),
      newLength: dco_decode_CastedPrimitive_usize(arr[1]),
      newCursor: dco_decode_CastedPrimitive_usize(arr[2]),
      cursorLine: dco_decode_CastedPrimitive_usize(arr[3]),
      cursorColumn: dco_decode_CastedPrimitive_usize(arr[4]),
      lineStartOffset: dco_decode_CastedPrimitive_usize(arr[5]),
      lineLength: dco_decode_CastedPrimitive_usize(arr[6]),
      lineCountChanged: dco_decode_bool(arr[7]),
      newLineCount: dco_decode_CastedPrimitive_usize(arr[8]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  ImeProjection dco_decode_ime_projection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ImeProjection(
      windowChanged: dco_decode_bool(arr[0]),
      windowStart: dco_decode_CastedPrimitive_usize(arr[1]),
      text: dco_decode_String(arr[2]),
      selectionBase: dco_decode_CastedPrimitive_usize(arr[3]),
      selectionExtent: dco_decode_CastedPrimitive_usize(arr[4]),
    );
  }

  @protected
  IndentInfo dco_decode_indent_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return IndentInfo(
      usesTabs: dco_decode_bool(arr[0]),
      spacesPerIndent: dco_decode_CastedPrimitive_usize(arr[1]),
      mixed: dco_decode_bool(arr[2]),
    );
  }

  @protected
  LineIndentInfo dco_decode_line_indent_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LineIndentInfo(
      tabs: dco_decode_CastedPrimitive_usize(arr[0]),
      spaces: dco_decode_CastedPrimitive_usize(arr[1]),
      lineBlank: dco_decode_bool(arr[2]),
    );
  }

  @protected
  List<int> dco_decode_list_CastedPrimitive_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_CastedPrimitive_usize)
        .toList();
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<LineIndentInfo> dco_decode_list_line_indent_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_line_indent_info).toList();
  }

  @protected
  List<MinimapLineDensity> dco_decode_list_minimap_line_density(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_minimap_line_density).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(int, int)>
      dco_decode_list_record_casted_primitive_usize_casted_primitive_usize(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_casted_primitive_usize_casted_primitive_usize)
        .toList();
  }

  @protected
  MinimapLineDensity dco_decode_minimap_line_density(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MinimapLineDensity(
      leadingWhitespace: dco_decode_CastedPrimitive_usize(arr[0]),
      contentLength: dco_decode_CastedPrimitive_usize(arr[1]),
      isEmpty: dco_decode_bool(arr[2]),
    );
  }

  @protected
  int? dco_decode_opt_CastedPrimitive_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_CastedPrimitive_usize(raw);
  }

  @protected
  List<(int, int)>?
      dco_decode_opt_list_record_casted_primitive_usize_casted_primitive_usize(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_list_record_casted_primitive_usize_casted_primitive_usize(
            raw);
  }

  @protected
  (int, int) dco_decode_record_casted_primitive_usize_casted_primitive_usize(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_CastedPrimitive_usize(arr[0]),
      dco_decode_CastedPrimitive_usize(arr[1]),
    );
  }

  @protected
  RopeMetrics dco_decode_rope_metrics(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RopeMetrics(
      byteLen: dco_decode_CastedPrimitive_usize(arr[0]),
      charLen: dco_decode_CastedPrimitive_usize(arr[1]),
      utf16Len: dco_decode_CastedPrimitive_usize(arr[2]),
      lineCount: dco_decode_CastedPrimitive_usize(arr[3]),
      maxLineUtf16Len: dco_decode_CastedPrimitive_usize(arr[4]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  RopeInstance
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RopeInstanceImpl.frbInternalSseDecode(
        sse_decode_i_64(deserializer).toInt(), sse_decode_i_32(deserializer));
  }

  @protected
  RopeInstance
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RopeInstanceImpl.frbInternalSseDecode(
        sse_decode_i_64(deserializer).toInt(), sse_decode_i_32(deserializer));
  }

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return inner.toInt();
  }

  @protected
  int sse_decode_CastedPrimitive_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_usize(deserializer);
    return inner.toInt();
  }

  @protected
  RopeInstance
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RopeInstanceImpl.frbInternalSseDecode(
        sse_decode_i_64(deserializer).toInt(), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CursorContext sse_decode_cursor_context(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_line = sse_decode_CastedPrimitive_usize(deserializer);
    var var_column = sse_decode_CastedPrimitive_usize(deserializer);
    var var_lineStartOffset = sse_decode_CastedPrimitive_usize(deserializer);
    var var_lineEndOffset = sse_decode_CastedPrimitive_usize(deserializer);
    var var_lineLength = sse_decode_CastedPrimitive_usize(deserializer);
    var var_totalLines = sse_decode_CastedPrimitive_usize(deserializer);
    var var_totalLength = sse_decode_CastedPrimitive_usize(deserializer);
    return CursorContext(
        line: var_line,
        column: var_column,
        lineStartOffset: var_lineStartOffset,
        lineEndOffset: var_lineEndOffset,
        lineLength: var_lineLength,
        totalLines: var_totalLines,
        totalLength: var_totalLength);
  }

  @protected
  DocumentTextSummary sse_decode_document_text_summary(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_len = sse_decode_CastedPrimitive_usize(deserializer);
    var var_chars = sse_decode_CastedPrimitive_usize(deserializer);
    var var_lenUtf16 = sse_decode_CastedPrimitive_usize(deserializer);
    var var_lines = sse_decode_CastedPrimitive_usize(deserializer);
    var var_lastLineColumn = sse_decode_CastedPrimitive_usize(deserializer);
    var var_firstLineChars = sse_decode_CastedPrimitive_usize(deserializer);
    var var_lastLineChars = sse_decode_CastedPrimitive_usize(deserializer);
    var var_lastLineLenUtf16 = sse_decode_CastedPrimitive_usize(deserializer);
    var var_longestRow = sse_decode_CastedPrimitive_usize(deserializer);
    var var_longestRowChars = sse_decode_CastedPrimitive_usize(deserializer);
    return DocumentTextSummary(
        len: var_len,
        chars: var_chars,
        lenUtf16: var_lenUtf16,
        lines: var_lines,
        lastLineColumn: var_lastLineColumn,
        firstLineChars: var_firstLineChars,
        lastLineChars: var_lastLineChars,
        lastLineLenUtf16: var_lastLineLenUtf16,
        longestRow: var_longestRow,
        longestRowChars: var_longestRowChars);
  }

  @protected
  EditResult sse_decode_edit_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deletedText = sse_decode_String(deserializer);
    var var_newLength = sse_decode_CastedPrimitive_usize(deserializer);
    var var_newCursor = sse_decode_CastedPrimitive_usize(deserializer);
    var var_cursorLine = sse_decode_CastedPrimitive_usize(deserializer);
    var var_cursorColumn = sse_decode_CastedPrimitive_usize(deserializer);
    var var_lineStartOffset = sse_decode_CastedPrimitive_usize(deserializer);
    var var_lineLength = sse_decode_CastedPrimitive_usize(deserializer);
    var var_lineCountChanged = sse_decode_bool(deserializer);
    var var_newLineCount = sse_decode_CastedPrimitive_usize(deserializer);
    return EditResult(
        deletedText: var_deletedText,
        newLength: var_newLength,
        newCursor: var_newCursor,
        cursorLine: var_cursorLine,
        cursorColumn: var_cursorColumn,
        lineStartOffset: var_lineStartOffset,
        lineLength: var_lineLength,
        lineCountChanged: var_lineCountChanged,
        newLineCount: var_newLineCount);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  ImeProjection sse_decode_ime_projection(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_windowChanged = sse_decode_bool(deserializer);
    var var_windowStart = sse_decode_CastedPrimitive_usize(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_selectionBase = sse_decode_CastedPrimitive_usize(deserializer);
    var var_selectionExtent = sse_decode_CastedPrimitive_usize(deserializer);
    return ImeProjection(
        windowChanged: var_windowChanged,
        windowStart: var_windowStart,
        text: var_text,
        selectionBase: var_selectionBase,
        selectionExtent: var_selectionExtent);
  }

  @protected
  IndentInfo sse_decode_indent_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_usesTabs = sse_decode_bool(deserializer);
    var var_spacesPerIndent = sse_decode_CastedPrimitive_usize(deserializer);
    var var_mixed = sse_decode_bool(deserializer);
    return IndentInfo(
        usesTabs: var_usesTabs,
        spacesPerIndent: var_spacesPerIndent,
        mixed: var_mixed);
  }

  @protected
  LineIndentInfo sse_decode_line_indent_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tabs = sse_decode_CastedPrimitive_usize(deserializer);
    var var_spaces = sse_decode_CastedPrimitive_usize(deserializer);
    var var_lineBlank = sse_decode_bool(deserializer);
    return LineIndentInfo(
        tabs: var_tabs, spaces: var_spaces, lineBlank: var_lineBlank);
  }

  @protected
  List<int> sse_decode_list_CastedPrimitive_usize(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <int>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_CastedPrimitive_usize(deserializer));
    }
    return ans_;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<LineIndentInfo> sse_decode_list_line_indent_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LineIndentInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_line_indent_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<MinimapLineDensity> sse_decode_list_minimap_line_density(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MinimapLineDensity>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_minimap_line_density(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(int, int)>
      sse_decode_list_record_casted_primitive_usize_casted_primitive_usize(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(int, int)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_casted_primitive_usize_casted_primitive_usize(
          deserializer));
    }
    return ans_;
  }

  @protected
  MinimapLineDensity sse_decode_minimap_line_density(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_leadingWhitespace = sse_decode_CastedPrimitive_usize(deserializer);
    var var_contentLength = sse_decode_CastedPrimitive_usize(deserializer);
    var var_isEmpty = sse_decode_bool(deserializer);
    return MinimapLineDensity(
        leadingWhitespace: var_leadingWhitespace,
        contentLength: var_contentLength,
        isEmpty: var_isEmpty);
  }

  @protected
  int? sse_decode_opt_CastedPrimitive_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_CastedPrimitive_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<(int, int)>?
      sse_decode_opt_list_record_casted_primitive_usize_casted_primitive_usize(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_record_casted_primitive_usize_casted_primitive_usize(
          deserializer));
    } else {
      return null;
    }
  }

  @protected
  (int, int) sse_decode_record_casted_primitive_usize_casted_primitive_usize(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_CastedPrimitive_usize(deserializer);
    var var_field1 = sse_decode_CastedPrimitive_usize(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RopeMetrics sse_decode_rope_metrics(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_byteLen = sse_decode_CastedPrimitive_usize(deserializer);
    var var_charLen = sse_decode_CastedPrimitive_usize(deserializer);
    var var_utf16Len = sse_decode_CastedPrimitive_usize(deserializer);
    var var_lineCount = sse_decode_CastedPrimitive_usize(deserializer);
    var var_maxLineUtf16Len = sse_decode_CastedPrimitive_usize(deserializer);
    return RopeMetrics(
        byteLen: var_byteLen,
        charLen: var_charLen,
        utf16Len: var_utf16Len,
        lineCount: var_lineCount,
        maxLineUtf16Len: var_maxLineUtf16Len);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          RopeInstance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as RopeInstanceImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          RopeInstance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as RopeInstanceImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(sseEncodeCastedPrimitiveI64(self), serializer);
  }

  @protected
  void sse_encode_CastedPrimitive_usize(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(sseEncodeCastedPrimitiveU64(self), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          RopeInstance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as RopeInstanceImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_cursor_context(CursorContext self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_usize(self.line, serializer);
    sse_encode_CastedPrimitive_usize(self.column, serializer);
    sse_encode_CastedPrimitive_usize(self.lineStartOffset, serializer);
    sse_encode_CastedPrimitive_usize(self.lineEndOffset, serializer);
    sse_encode_CastedPrimitive_usize(self.lineLength, serializer);
    sse_encode_CastedPrimitive_usize(self.totalLines, serializer);
    sse_encode_CastedPrimitive_usize(self.totalLength, serializer);
  }

  @protected
  void sse_encode_document_text_summary(
      DocumentTextSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_usize(self.len, serializer);
    sse_encode_CastedPrimitive_usize(self.chars, serializer);
    sse_encode_CastedPrimitive_usize(self.lenUtf16, serializer);
    sse_encode_CastedPrimitive_usize(self.lines, serializer);
    sse_encode_CastedPrimitive_usize(self.lastLineColumn, serializer);
    sse_encode_CastedPrimitive_usize(self.firstLineChars, serializer);
    sse_encode_CastedPrimitive_usize(self.lastLineChars, serializer);
    sse_encode_CastedPrimitive_usize(self.lastLineLenUtf16, serializer);
    sse_encode_CastedPrimitive_usize(self.longestRow, serializer);
    sse_encode_CastedPrimitive_usize(self.longestRowChars, serializer);
  }

  @protected
  void sse_encode_edit_result(EditResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deletedText, serializer);
    sse_encode_CastedPrimitive_usize(self.newLength, serializer);
    sse_encode_CastedPrimitive_usize(self.newCursor, serializer);
    sse_encode_CastedPrimitive_usize(self.cursorLine, serializer);
    sse_encode_CastedPrimitive_usize(self.cursorColumn, serializer);
    sse_encode_CastedPrimitive_usize(self.lineStartOffset, serializer);
    sse_encode_CastedPrimitive_usize(self.lineLength, serializer);
    sse_encode_bool(self.lineCountChanged, serializer);
    sse_encode_CastedPrimitive_usize(self.newLineCount, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_ime_projection(ImeProjection self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.windowChanged, serializer);
    sse_encode_CastedPrimitive_usize(self.windowStart, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_CastedPrimitive_usize(self.selectionBase, serializer);
    sse_encode_CastedPrimitive_usize(self.selectionExtent, serializer);
  }

  @protected
  void sse_encode_indent_info(IndentInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.usesTabs, serializer);
    sse_encode_CastedPrimitive_usize(self.spacesPerIndent, serializer);
    sse_encode_bool(self.mixed, serializer);
  }

  @protected
  void sse_encode_line_indent_info(
      LineIndentInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_usize(self.tabs, serializer);
    sse_encode_CastedPrimitive_usize(self.spaces, serializer);
    sse_encode_bool(self.lineBlank, serializer);
  }

  @protected
  void sse_encode_list_CastedPrimitive_usize(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_CastedPrimitive_usize(item, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_line_indent_info(
      List<LineIndentInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_line_indent_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_minimap_line_density(
      List<MinimapLineDensity> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_minimap_line_density(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_casted_primitive_usize_casted_primitive_usize(
      List<(int, int)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_casted_primitive_usize_casted_primitive_usize(
          item, serializer);
    }
  }

  @protected
  void sse_encode_minimap_line_density(
      MinimapLineDensity self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_usize(self.leadingWhitespace, serializer);
    sse_encode_CastedPrimitive_usize(self.contentLength, serializer);
    sse_encode_bool(self.isEmpty, serializer);
  }

  @protected
  void sse_encode_opt_CastedPrimitive_usize(
      int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_CastedPrimitive_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_record_casted_primitive_usize_casted_primitive_usize(
      List<(int, int)>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_record_casted_primitive_usize_casted_primitive_usize(
          self, serializer);
    }
  }

  @protected
  void sse_encode_record_casted_primitive_usize_casted_primitive_usize(
      (int, int) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_usize(self.$1, serializer);
    sse_encode_CastedPrimitive_usize(self.$2, serializer);
  }

  @protected
  void sse_encode_rope_metrics(RopeMetrics self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_usize(self.byteLen, serializer);
    sse_encode_CastedPrimitive_usize(self.charLen, serializer);
    sse_encode_CastedPrimitive_usize(self.utf16Len, serializer);
    sse_encode_CastedPrimitive_usize(self.lineCount, serializer);
    sse_encode_CastedPrimitive_usize(self.maxLineUtf16Len, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class RopeInstanceImpl extends RustOpaque implements RopeInstance {
  // Not to be used by end users
  RopeInstanceImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RopeInstanceImpl.frbInternalSseDecode(int ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_RopeInstance,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_RopeInstance,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_RopeInstancePtr,
  );
}
