// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_RopeInstancePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RopeInstance
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          dynamic raw);

  @protected
  RopeInstance
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_usize(dynamic raw);

  @protected
  RopeInstance
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          dynamic raw);

  @protected
  RustStreamSink<OrchestrateEvent> dco_decode_StreamSink_orchestrate_event_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AgentBackendConfig dco_decode_agent_backend_config(dynamic raw);

  @protected
  AgentContextBudget dco_decode_agent_context_budget(dynamic raw);

  @protected
  AgentEditResult dco_decode_agent_edit_result(dynamic raw);

  @protected
  AgentResponse dco_decode_agent_response(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AgentContextBudget dco_decode_box_autoadd_agent_context_budget(dynamic raw);

  @protected
  AgentResponse dco_decode_box_autoadd_agent_response(dynamic raw);

  @protected
  OrchestrateRequest dco_decode_box_autoadd_orchestrate_request(dynamic raw);

  @protected
  CursorContext dco_decode_cursor_context(dynamic raw);

  @protected
  DocumentTextSummary dco_decode_document_text_summary(dynamic raw);

  @protected
  EditResult dco_decode_edit_result(dynamic raw);

  @protected
  EditorAction dco_decode_editor_action(dynamic raw);

  @protected
  EditorActionKind dco_decode_editor_action_kind(dynamic raw);

  @protected
  FileReference dco_decode_file_reference(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImeProjection dco_decode_ime_projection(dynamic raw);

  @protected
  IndentInfo dco_decode_indent_info(dynamic raw);

  @protected
  LineIndentInfo dco_decode_line_indent_info(dynamic raw);

  @protected
  List<int> dco_decode_list_CastedPrimitive_usize(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<EditorAction> dco_decode_list_editor_action(dynamic raw);

  @protected
  List<FileReference> dco_decode_list_file_reference(dynamic raw);

  @protected
  List<LineIndentInfo> dco_decode_list_line_indent_info(dynamic raw);

  @protected
  List<MinimapLineDensity> dco_decode_list_minimap_line_density(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(int, int)>
      dco_decode_list_record_casted_primitive_usize_casted_primitive_usize(
          dynamic raw);

  @protected
  MinimapLineDensity dco_decode_minimap_line_density(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_usize(dynamic raw);

  @protected
  List<(int, int)>?
      dco_decode_opt_list_record_casted_primitive_usize_casted_primitive_usize(
          dynamic raw);

  @protected
  OrchestrateEvent dco_decode_orchestrate_event(dynamic raw);

  @protected
  OrchestrateRequest dco_decode_orchestrate_request(dynamic raw);

  @protected
  RangeContext dco_decode_range_context(dynamic raw);

  @protected
  (int, int) dco_decode_record_casted_primitive_usize_casted_primitive_usize(
      dynamic raw);

  @protected
  RopeMetrics dco_decode_rope_metrics(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RopeInstance
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          SseDeserializer deserializer);

  @protected
  RopeInstance
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_usize(SseDeserializer deserializer);

  @protected
  RopeInstance
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<OrchestrateEvent> sse_decode_StreamSink_orchestrate_event_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AgentBackendConfig sse_decode_agent_backend_config(
      SseDeserializer deserializer);

  @protected
  AgentContextBudget sse_decode_agent_context_budget(
      SseDeserializer deserializer);

  @protected
  AgentEditResult sse_decode_agent_edit_result(SseDeserializer deserializer);

  @protected
  AgentResponse sse_decode_agent_response(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AgentContextBudget sse_decode_box_autoadd_agent_context_budget(
      SseDeserializer deserializer);

  @protected
  AgentResponse sse_decode_box_autoadd_agent_response(
      SseDeserializer deserializer);

  @protected
  OrchestrateRequest sse_decode_box_autoadd_orchestrate_request(
      SseDeserializer deserializer);

  @protected
  CursorContext sse_decode_cursor_context(SseDeserializer deserializer);

  @protected
  DocumentTextSummary sse_decode_document_text_summary(
      SseDeserializer deserializer);

  @protected
  EditResult sse_decode_edit_result(SseDeserializer deserializer);

  @protected
  EditorAction sse_decode_editor_action(SseDeserializer deserializer);

  @protected
  EditorActionKind sse_decode_editor_action_kind(SseDeserializer deserializer);

  @protected
  FileReference sse_decode_file_reference(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImeProjection sse_decode_ime_projection(SseDeserializer deserializer);

  @protected
  IndentInfo sse_decode_indent_info(SseDeserializer deserializer);

  @protected
  LineIndentInfo sse_decode_line_indent_info(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_CastedPrimitive_usize(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<EditorAction> sse_decode_list_editor_action(
      SseDeserializer deserializer);

  @protected
  List<FileReference> sse_decode_list_file_reference(
      SseDeserializer deserializer);

  @protected
  List<LineIndentInfo> sse_decode_list_line_indent_info(
      SseDeserializer deserializer);

  @protected
  List<MinimapLineDensity> sse_decode_list_minimap_line_density(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(int, int)>
      sse_decode_list_record_casted_primitive_usize_casted_primitive_usize(
          SseDeserializer deserializer);

  @protected
  MinimapLineDensity sse_decode_minimap_line_density(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_usize(SseDeserializer deserializer);

  @protected
  List<(int, int)>?
      sse_decode_opt_list_record_casted_primitive_usize_casted_primitive_usize(
          SseDeserializer deserializer);

  @protected
  OrchestrateEvent sse_decode_orchestrate_event(SseDeserializer deserializer);

  @protected
  OrchestrateRequest sse_decode_orchestrate_request(
      SseDeserializer deserializer);

  @protected
  RangeContext sse_decode_range_context(SseDeserializer deserializer);

  @protected
  (int, int) sse_decode_record_casted_primitive_usize_casted_primitive_usize(
      SseDeserializer deserializer);

  @protected
  RopeMetrics sse_decode_rope_metrics(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          RopeInstance self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          RopeInstance self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_usize(int self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          RopeInstance self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_orchestrate_event_Sse(
      RustStreamSink<OrchestrateEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_agent_backend_config(
      AgentBackendConfig self, SseSerializer serializer);

  @protected
  void sse_encode_agent_context_budget(
      AgentContextBudget self, SseSerializer serializer);

  @protected
  void sse_encode_agent_edit_result(
      AgentEditResult self, SseSerializer serializer);

  @protected
  void sse_encode_agent_response(AgentResponse self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_agent_context_budget(
      AgentContextBudget self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_agent_response(
      AgentResponse self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_orchestrate_request(
      OrchestrateRequest self, SseSerializer serializer);

  @protected
  void sse_encode_cursor_context(CursorContext self, SseSerializer serializer);

  @protected
  void sse_encode_document_text_summary(
      DocumentTextSummary self, SseSerializer serializer);

  @protected
  void sse_encode_edit_result(EditResult self, SseSerializer serializer);

  @protected
  void sse_encode_editor_action(EditorAction self, SseSerializer serializer);

  @protected
  void sse_encode_editor_action_kind(
      EditorActionKind self, SseSerializer serializer);

  @protected
  void sse_encode_file_reference(FileReference self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_ime_projection(ImeProjection self, SseSerializer serializer);

  @protected
  void sse_encode_indent_info(IndentInfo self, SseSerializer serializer);

  @protected
  void sse_encode_line_indent_info(
      LineIndentInfo self, SseSerializer serializer);

  @protected
  void sse_encode_list_CastedPrimitive_usize(
      List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_editor_action(
      List<EditorAction> self, SseSerializer serializer);

  @protected
  void sse_encode_list_file_reference(
      List<FileReference> self, SseSerializer serializer);

  @protected
  void sse_encode_list_line_indent_info(
      List<LineIndentInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_minimap_line_density(
      List<MinimapLineDensity> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_casted_primitive_usize_casted_primitive_usize(
      List<(int, int)> self, SseSerializer serializer);

  @protected
  void sse_encode_minimap_line_density(
      MinimapLineDensity self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_usize(
      int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_record_casted_primitive_usize_casted_primitive_usize(
      List<(int, int)>? self, SseSerializer serializer);

  @protected
  void sse_encode_orchestrate_event(
      OrchestrateEvent self, SseSerializer serializer);

  @protected
  void sse_encode_orchestrate_request(
      OrchestrateRequest self, SseSerializer serializer);

  @protected
  void sse_encode_range_context(RangeContext self, SseSerializer serializer);

  @protected
  void sse_encode_record_casted_primitive_usize_casted_primitive_usize(
      (int, int) self, SseSerializer serializer);

  @protected
  void sse_encode_rope_metrics(RopeMetrics self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeInstance(
          int ptr);
}
